#ifndef WIZZARDPOST_H
#define WIZZARDPOST_H

#ifndef CHANNEL1_FUNC
#define CHANNEL1_FUNC CHANFUNC_UNDEFINED
#endif

#ifndef CHANNEL2_FUNC
#define CHANNEL2_FUNC CHANFUNC_UNDEFINED
#endif

#ifndef CHANNEL3_FUNC
#define CHANNEL3_FUNC CHANFUNC_UNDEFINED
#endif

#ifndef CHANNEL4_FUNC
#define CHANNEL4_FUNC CHANFUNC_UNDEFINED
#endif

#ifndef CHANNEL1_GAIN
#define CHANNEL1_GAIN 100
#endif

#ifndef CHANNEL2_GAIN
#define CHANNEL2_GAIN 100
#endif

#ifndef CHANNEL3_GAIN
#define CHANNEL3_GAIN 100
#endif

#ifndef CHANNEL4_GAIN
#define CHANNEL4_GAIN 100
#endif

#ifndef CHANNEL1_POSLIMIT
#define CHANNEL1_POSLIMIT CHANLIMIT_NONE
#endif

#ifndef CHANNEL2_POSLIMIT
#define CHANNEL2_POSLIMIT CHANLIMIT_NONE
#endif

#ifndef CHANNEL3_POSLIMIT
#define CHANNEL3_POSLIMIT CHANLIMIT_NONE
#endif

#ifndef CHANNEL4_POSLIMIT
#define CHANNEL4_POSLIMIT CHANLIMIT_NONE
#endif

#ifndef CHANNEL1_NEGLIMIT
#define CHANNEL1_NEGLIMIT CHANLIMIT_NONE
#endif

#ifndef CHANNEL2_NEGLIMIT
#define CHANNEL2_NEGLIMIT CHANLIMIT_NONE
#endif

#ifndef CHANNEL3_NEGLIMIT
#define CHANNEL3_NEGLIMIT CHANLIMIT_NONE
#endif

#ifndef CHANNEL4_NEGLIMIT
#define CHANNEL4_NEGLIMIT CHANLIMIT_NONE
#endif

#ifndef CHANNEL1_POSTHRESH
#define CHANNEL1_POSTHRESH  20
#endif

#ifndef CHANNEL2_POSTHRESH
#define CHANNEL2_POSTHRESH  20
#endif

#ifndef CHANNEL3_POSTHRESH
#define CHANNEL3_POSTHRESH  20
#endif

#ifndef CHANNEL4_POSTHRESH
#define CHANNEL4_POSTHRESH  20
#endif

#ifndef CHANNEL1_NEGTHRESH
#define CHANNEL1_NEGTHRESH  20
#endif

#ifndef CHANNEL2_NEGTHRESH
#define CHANNEL2_NEGTHRESH  20
#endif

#ifndef CHANNEL3_NEGTHRESH
#define CHANNEL3_NEGTHRESH  20
#endif

#ifndef CHANNEL4_NEGTHRESH
#define CHANNEL4_NEGTHRESH  20
#endif

#ifndef CHANNEL1_SERVO
#define CHANNEL1_SERVO CHAN_NOSERVOOUT
#endif

#ifndef CHANNEL2_SERVO
#define CHANNEL2_SERVO CHAN_NOSERVOOUT
#endif
#ifndef CHANNEL3_SERVO
#define CHANNEL3_SERVO CHAN_NOSERVOOUT
#endif
#ifndef CHANNEL4_SERVO
#define CHANNEL4_SERVO CHAN_NOSERVOOUT
#endif
#endif
